version: '1.0'

trigger:
- dev
stages:
  - prepare
  - build

steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'KevinOspina/ll-backend-test'
    revision: dev
    git: github
  BuildingDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: gradle-sample-app
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile